#!/bin/bash
#
# Build code coverage information.
# 1) Only works on linux

echo ''
echo 'EUROPA code test case coverage anlaysis script - uses gcov'
echo ''

jam -sVARIANTS=COVERAGE -sLIBRARIES=STATIC run-solvers-module-tests # ensure required .xml files get built. Cheaper than adding dependancy information to System/test jamfile.
jam -sVARIANTS=COVERAGE -sLIBRARIES=STATIC run-all-module-tests

javac ./System/test/Java/RunGcov.java
java  -classpath ./System/test/Java RunGcov coverage-results.txt .

exit 0
