#!/bin/sh

cd ..

# McGann/CBPlanner -> PLASMA/CBPlanner

cp McGann/CBPlanner/CBPlanner.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/CBPlanner.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/CBPlannerDefs.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/Choice.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/Choice.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/Condition.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/Condition.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DMCEListener.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DMCEListener.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DMDBListener.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DMDBListener.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DecisionManager.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DecisionManager.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DecisionManagerListener.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DecisionManagerListener.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DecisionPoint.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/DecisionPoint.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/Horizon.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/Horizon.cc PLASMA/CBPlanner/core/
cp McGann/CBPlanner/OpenDecisionManager.hh PLASMA/CBPlanner/core/
cp McGann/CBPlanner/OpenDecisionManager.cc PLASMA/CBPlanner/core/

cp McGann/CBPlanner/CBPlannerDefs.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/ConstrainedVariableDecisionPoint.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/ConstrainedVariableDecisionPoint.cc PLASMA/CBPlanner/component/
cp McGann/CBPlanner/DMLogger.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/DMLogger.cc PLASMA/CBPlanner/component/
cp McGann/CBPlanner/DynamicInfiniteRealCondition.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/DynamicInfiniteRealCondition.cc PLASMA/CBPlanner/component/
cp McGann/CBPlanner/HorizonCondition.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/HorizonCondition.cc PLASMA/CBPlanner/component/
cp McGann/CBPlanner/ObjectDecisionPoint.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/ObjectDecisionPoint.cc PLASMA/CBPlanner/component/
cp McGann/CBPlanner/TemporalVariableCondition.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/TemporalVariableCondition.cc PLASMA/CBPlanner/component/
cp McGann/CBPlanner/TokenDecisionPoint.hh PLASMA/CBPlanner/component/
cp McGann/CBPlanner/TokenDecisionPoint.cc PLASMA/CBPlanner/component/

cp McGann/CBPlanner/SubgoalOnceRule.hh PLASMA/CBPlanner/test/
cp McGann/CBPlanner/SubgoalOnceRule.cc PLASMA/CBPlanner/test/
cp McGann/CBPlanner/module-tests.cc PLASMA/CBPlanner/test/

# McGann/ConstraintEngine -> PLASMA/Utils

cp McGann/ConstraintEngine/CommonDefs.hh PLASMA/Utils/core/
cp McGann/ConstraintEngine/Entity.cc PLASMA/Utils/core/
cp McGann/ConstraintEngine/Entity.hh PLASMA/Utils/core/
cp McGann/ConstraintEngine/Id.hh PLASMA/Utils/core/
cp McGann/ConstraintEngine/IdTable.cc PLASMA/Utils/core/
cp McGann/ConstraintEngine/IdTable.hh PLASMA/Utils/core/
cp McGann/ConstraintEngine/LabelStr.cc PLASMA/Utils/core/
cp McGann/ConstraintEngine/LabelStr.hh PLASMA/Utils/core/
cp McGann/ConstraintEngine/Utils.cc PLASMA/Utils/core/
cp McGann/ConstraintEngine/Utils.hh PLASMA/Utils/core/
cp McGann/ConstraintEngine/error.cc PLASMA/Utils/core/
cp McGann/ConstraintEngine/error.hh PLASMA/Utils/core/

# McGann/ConstraintEngine -> PLASMA/ConstraintEngine

cp McGann/ConstraintEngine/main_page.hh PLASMA/ConstraintEngine/documentation/

cp McGann/ConstraintEngine/AbstractDomain.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/AbstractDomain.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstrainedVariable.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstrainedVariable.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/Constraint.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/Constraint.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstraintEngine.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstraintEngine.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstraintEngineDefs.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstraintEngineListener.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstraintEngineListener.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstraintLibrary.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/ConstraintLibrary.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/DomainListener.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/Propagator.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/Propagator.hh PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/VariableChangeListener.cc PLASMA/ConstraintEngine/core/
cp McGann/ConstraintEngine/VariableChangeListener.hh PLASMA/ConstraintEngine/core/

cp McGann/ConstraintEngine/BoolDomain.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/BoolDomain.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/CeLogger.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/CeLogger.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/ConstraintEngineDefs.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/Constraints.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/Constraints.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/Domain.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/DefaultPropagator.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/DefaultPropagator.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/EqualityConstraintPropagator.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/EqualityConstraintPropagator.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/EquivalenceClassCollection.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/EquivalenceClassCollection.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/EnumeratedDomain.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/EnumeratedDomain.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/IntervalDomain.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/IntervalDomain.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/IntervalIntDomain.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/IntervalIntDomain.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/TestSupport.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/UnaryConstraint.cc PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/UnaryConstraint.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/Variable.hh PLASMA/ConstraintEngine/component/
cp McGann/ConstraintEngine/test-support.cc PLASMA/ConstraintEngine/component/

cp McGann/ConstraintEngine/DomainTest.cc PLASMA/ConstraintEngine/test/
cp McGann/ConstraintEngine/domain-tests.cc PLASMA/ConstraintEngine/test/
cp McGann/ConstraintEngine/domain-tests.hh PLASMA/ConstraintEngine/test/
cp McGann/ConstraintEngine/module-tests.cc PLASMA/ConstraintEngine/test/
cp McGann/ConstraintEngine/module-tests.hh PLASMA/ConstraintEngine/test/
cp McGann/ConstraintEngine/id-tests.cc PLASMA/ConstraintEngine/test/

cp McGann/ConstraintEngine/CLibTestCases PLASMA/ConstraintEngine/test/
cp McGann/ConstraintEngine/NewTestCases PLASMA/ConstraintEngine/test/

# will not be migrated:
# cp McGann/ConstraintEngine/EuropaDomainTest.cc
# cp McGann/ConstraintEngine/InstrumentationLogger.hh

# McGann/java/antlr -> PLASMA/NDDL/core/antlr/

cp McGann/java/antlr/nddl.g PLASMA/NDDL/core/antlr/
cp McGann/java/antlr/nddl.dtd PLASMA/NDDL/core/antlr/
cp McGann/java/antlr/nddl.tree.g PLASMA/NDDL/core/antlr/

# McGann/java/lib -> PLASMA/NDDL/core/libraries/

cp McGann/java/lib/antlr.jar PLASMA/NDDL/core/libraries/
cp McGann/java/lib/nanoxml.jar PLASMA/NDDL/core/libraries/

# McGann/java/src/nddl -> PLASMA/NDDL/core/java/nddl/

cp McGann/java/src/nddl/ClassWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/ConstraintWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/EnumerationWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/HeaderGenerator.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/ImplementationGenerator.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/IndentWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/NddlASTFactory.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/NddlASTNode.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/NddlCompiler.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/NddlToken.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/NddlXmlStrings.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/Parse.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/PredicateWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/RuleWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/SchemaWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/SharedWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/VariableWriter.java PLASMA/NDDL/core/java/nddl/
cp McGann/java/src/nddl/XMLUtil.java PLASMA/NDDL/core/java/nddl/

# McGann/java/tests -> PLASMA/NDDL/test/parser/

cp McGann/java/tests/BasicClassDeclarations.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/DNP-transliteration.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/allocationTests.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/attributedTemporalRelations.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/camera.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/constraints.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/constructorTests.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/enumTests.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/existentialQuantification.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/extendQualified.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/globals.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/includer.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/initial-state.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/initializerTests.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/inner-classes.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/inner-enums.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/keyword-example.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/labeledSubgoals.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/local-vars.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/location.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/missionaries.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/multipleSubgoals.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/otherFile.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/pns-conf-test.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/predicatePrototypes.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/rover-camera.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/rover.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/simpleInstantiation.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/structureTests.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/switchTests.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/temporalNumericIntervals.nddl PLASMA/NDDL/test/parser/
cp McGann/java/tests/transitional-subgoaling.nddl PLASMA/NDDL/test/parser/

# McGann/NddlCompiler -> PLASMA/NDDL

cp McGann/NddlCompiler/Nddl.hh PLASMA/NDDL/core/
cp McGann/NddlCompiler/NddlUtils.cc PLASMA/NDDL/core/
cp McGann/NddlCompiler/NddlUtils.hh PLASMA/NDDL/core/

cp McGann/NddlCompiler/module-tests.cc PLASMA/NDDL/test/

# temporary
cp McGann/NddlCompiler/Plasma.nddl PLASMA/NDDL/test/
cp McGann/NddlCompiler/Resources.nddl PLASMA/NDDL/test/

# McGann/NddlCompiler/test -> PLASMA/NDDL/test/compiler/

cp McGann/NddlCompiler/test/class-constructor.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/existential.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/guards.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/interval-constants.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/less-basic-model.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/multi-resources.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/no-world.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/plasma-base.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/simple-class.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/simple-predicate.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/simple-resources.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/simple-rules.nddl PLASMA/NDDL/test/compiler/
cp McGann/NddlCompiler/test/subclass.nddl PLASMA/NDDL/test/compiler/

# McGann/PlanDatabase -> PLASMA/Planner/component/

cp McGann/PlanDatabase/PartialPlanWriter.cc PLASMA/CBPlanner/component/

# McGann/PlanDatabase -> PLASMA/PlanDatabase

cp McGann/PlanDatabase/CommonAncestorConstraint.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/CommonAncestorConstraint.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/DbClient.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/DbClient.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/DbClientListener.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/DefaultTemporalAdvisor.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/DefaultTemporalAdvisor.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/HasAncestorConstraint.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/HasAncestorConstraint.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/MergeMemento.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/MergeMemento.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/Object.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/Object.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/ObjectFactory.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/ObjectFactory.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/ObjectTokenRelation.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/ObjectTokenRelation.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/PlanDatabase.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/PlanDatabase.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/PlanDatabaseDefs.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/PlanDatabaseListener.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/PlanDatabaseListener.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/Schema.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/StackMemento.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/StackMemento.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/TemporalAdvisor.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/Token.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/Token.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/TokenFactory.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/TokenFactory.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/TokenVariable.hh PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/UnifyMemento.cc PLASMA/PlanDatabase/core/
cp McGann/PlanDatabase/UnifyMemento.hh PLASMA/PlanDatabase/core/

cp McGann/PlanDatabase/Db.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/DbClientTransactionLog.cc PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/DbClientTransactionLog.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/DbClientTransactionPlayer.cc PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/DbClientTransactionPlayer.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/DbLogger.cc PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/DbLogger.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/EventToken.cc PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/EventToken.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/IntervalToken.cc PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/IntervalToken.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/PartialPlanWriter.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/PlanDatabaseDefs.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/PlanDatabaseWriter.hh PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/Timeline.cc PLASMA/PlanDatabase/component/
cp McGann/PlanDatabase/Timeline.hh PLASMA/PlanDatabase/component/

cp McGann/PlanDatabase/module-tests.cc PLASMA/PlanDatabase/test/

# McGann/Resource -> PLASMA/Resource

cp McGann/Resource/Resource.cc PLASMA/Resource/core/
cp McGann/Resource/Resource.hh PLASMA/Resource/core/
cp McGann/Resource/ResourceDefs.hh PLASMA/Resource/core/

cp McGann/Resource/ResourceConstraint.cc PLASMA/Resource/component/
cp McGann/Resource/ResourceConstraint.hh PLASMA/Resource/component/
cp McGann/Resource/ResourceDefs.hh PLASMA/Resource/component/
cp McGann/Resource/ResourcePropagator.cc PLASMA/Resource/component/
cp McGann/Resource/ResourcePropagator.hh PLASMA/Resource/component/
cp McGann/Resource/ResourceTransactionConstraint.cc PLASMA/Resource/component/
cp McGann/Resource/ResourceTransactionConstraint.hh PLASMA/Resource/component/
cp McGann/Resource/Transaction.cc PLASMA/Resource/component/
cp McGann/Resource/Transaction.hh PLASMA/Resource/component/

cp McGann/Resource/module-tests.cc PLASMA/Resource/test/

# McGann/RulesEngine -> PLASMA/RulesEngine

cp McGann/RulesEngine/RulesEngine.cc PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RulesEngine.hh PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RulesEngineListener.cc PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RulesEngineListener.hh PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RulesEngineDefs.hh PLASMA/RulesEngine/core/
cp McGann/RulesEngine/Rule.cc PLASMA/RulesEngine/core/
cp McGann/RulesEngine/Rule.hh PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RuleInstance.cc PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RuleInstance.hh PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RuleVariableListener.cc PLASMA/RulesEngine/core/
cp McGann/RulesEngine/RuleVariableListener.hh PLASMA/RulesEngine/core/

cp McGann/RulesEngine/TestRule.cc PLASMA/RulesEngine/test/
cp McGann/RulesEngine/TestRule.hh PLASMA/RulesEngine/test/
cp McGann/RulesEngine/module-tests.cc PLASMA/RulesEngine/test/

# McGann/RulesEngine -> PLASMA/PlanDatabase

# attn:
cp McGann/RulesEngine/ObjectFilter.cc PLASMA/PlanDatabase/component/
cp McGann/RulesEngine/ObjectFilter.hh PLASMA/PlanDatabase/component/

# McGann/SystemTests -> PLASMA/System

cp McGann/SystemTests/PrototypePerformanceConstraint.cc PLASMA/System/core/
cp McGann/SystemTests/PrototypePerformanceConstraint.hh PLASMA/System/core/
cp McGann/SystemTests/SamplePlanDatabase.hh PLASMA/System/core/

cp McGann/SystemTests/runInitialTest.cc PLASMA/System/test/
cp McGann/SystemTests/runTest.cc PLASMA/System/test/
cp McGann/SystemTests/runTransactionTest.cc PLASMA/System/test/
cp McGann/SystemTests/stackGenerator.cc PLASMA/System/test/
cp McGann/SystemTests/NddlWorld.nddl PLASMA/System/test/
cp McGann/SystemTests/Rover-transaction.nddl PLASMA/System/test/
cp McGann/SystemTests/Rover.nddl PLASMA/System/test/
cp McGann/SystemTests/basic-model-transaction.nddl PLASMA/System/test/
cp McGann/SystemTests/basic-model.nddl PLASMA/System/test/
cp McGann/SystemTests/basic-model.res.nddl PLASMA/System/test/
cp McGann/SystemTests/k9-initial.nddl PLASMA/System/test/
cp McGann/SystemTests/k9-transaction.nddl PLASMA/System/test/
cp McGann/SystemTests/k9.backtrack.moderate-transaction.nddl PLASMA/System/test/
cp McGann/SystemTests/k9.backtrack.moderate.nddl PLASMA/System/test/
cp McGann/SystemTests/k9.huge.nddl PLASMA/System/test/
cp McGann/SystemTests/k9.model.backtrack.moderate.nddl PLASMA/System/test/
cp McGann/SystemTests/k9.model.nddl PLASMA/System/test/
cp McGann/SystemTests/k9.nddl PLASMA/System/test/
cp McGann/SystemTests/path-filter-transaction.nddl PLASMA/System/test/
cp McGann/SystemTests/path-filter.nddl PLASMA/System/test/

# will not be migrated
# cp McGann/SystemTests/Rover.Round0.nddl PLASMA/System/test/
# cp McGann/SystemTests/Rover.Round1.nddl PLASMA/System/test/
# cp McGann/SystemTests/Rover.Round2.nddl PLASMA/System/test/
# cp McGann/SystemTests/Rover.Round3.nddl PLASMA/System/test/
# cp McGann/SystemTests/Rover.Round4.nddl PLASMA/System/test/
# cp McGann/SystemTests/Rover.Round6.nddl PLASMA/System/test/

# McGann/TemporalNetwork -> PLASMA/Utils

cp McGann/TemporalNetwork/HashPriorityQueue.hh PLASMA/Utils/core/

# McGann/TemporalNetwork -> PLASMA/TemporalNetwork

cp McGann/TemporalNetwork/DispatchGraph.cc PLASMA/TemporalNetwork/core/
cp McGann/TemporalNetwork/DispatchGraph.hh PLASMA/TemporalNetwork/core/
cp McGann/TemporalNetwork/DistanceGraph.cc PLASMA/TemporalNetwork/core/
cp McGann/TemporalNetwork/DistanceGraph.hh PLASMA/TemporalNetwork/core/
cp McGann/TemporalNetwork/TemporalNetwork.cc PLASMA/TemporalNetwork/core/
cp McGann/TemporalNetwork/TemporalNetwork.hh PLASMA/TemporalNetwork/core/
cp McGann/TemporalNetwork/TemporalNetworkDefs.hh PLASMA/TemporalNetwork/core/
cp McGann/TemporalNetwork/queues.cc PLASMA/TemporalNetwork/core/

cp McGann/TemporalNetwork/STNTemporalAdvisor.cc PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/STNTemporalAdvisor.hh PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TemporalNetworkLogger.cc PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TemporalNetworkLogger.hh PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TemporalNetworkListener.cc PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TemporalNetworkListener.hh PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TemporalPropagator.cc PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TemporalPropagator.hh PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TimepointWrapper.cc PLASMA/TemporalNetwork/component/
cp McGann/TemporalNetwork/TimepointWrapper.hh PLASMA/TemporalNetwork/component/

cp McGann/TemporalNetwork/module-tests.cc PLASMA/TemporalNetwork/test/

# McGann/TinyXml

cp McGann/TinyXml/tinyxml_2_2_1.tar.gz PLASMA/TinyXml/
cp McGann/TinyXml/readme.txt PLASMA/TinyXml/
cp McGann/TinyXml/changes.txt PLASMA/TinyXml/

cp McGann/TinyXml/docs/*.html PLASMA/TinyXml/documentation/
cp McGann/TinyXml/docs/*.gif PLASMA/TinyXml/documentation/
cp McGann/TinyXml/docs/doxygen.* PLASMA/TinyXml/documentation/

cp McGann/TinyXml/sstream PLASMA/TinyXml/core/
cp McGann/TinyXml/tinyxml.cpp PLASMA/TinyXml/core/
cp McGann/TinyXml/tinyxml.h PLASMA/TinyXml/core/
cp McGann/TinyXml/tinyxmlparser.cpp PLASMA/TinyXml/core/
cp McGann/TinyXml/tinyxmlerror.cpp PLASMA/TinyXml/core/
cp McGann/TinyXml/tinystr.h PLASMA/TinyXml/core/
cp McGann/TinyXml/tinystr.cpp PLASMA/TinyXml/core/

cp McGann/TinyXml/xmltest.cpp PLASMA/TinyXml/test/

cp McGann/TinyXml/sstream PLASMA/Utils/core/
