#!/bin/bash
NDDL=`dirname "$0"`/NDDL/core
TL=`dirname "$0"`/System/component
if [ -n $JAVA ]; then
  if [ -n $JAVA_HOME ]; then
    JAVA=$JAVA_HOME/bin/java;
  else
    JAVA=java;
  fi;
fi
$JAVA -cp $NDDL/libraries/nanoxml.jar:$NDDL/libraries/antlr.jar:$TL/jars/testLang.jar testLang.TestLangXMLToCpp "./$1"
