#!/bin/bash

PLASMA=`dirname "$0"`
if [ -n $CPP ]; then
    if [ -n $GCC_ROOTDIR ]; then
        CPP="g++"
    else
        CPP="$GCC_ROOTDIR/bin/g++"
    fi;
fi

if [[ -z $1 || -z $2 || -z $3 || -z $4 || -z $5 ]]; then
    echo "Usage: testlanglink <suffix> <dest> <model> <test> <runner>"
    exit -1;
fi

suf=$1
dest=$2
model=$3
test=$4
runner=$5

jam $model
jam $runner

#testlanglink dest model test runner

$CPP -o ./$dest ./$model ./$test ./$runner $PLASMA/NDDL/objects/libNDDL_$suf.a $PLASMA/TemporalNetwork/objects/libTemporalNetwork_$suf.a $PLASMA/System/objects/libSystem_$suf.a $PLASMA/CBPlanner/objects/libCBPlanner_$suf.a $PLASMA/RulesEngine/objects/libRulesEngine_$suf.a $PLASMA/Resource/objects/libResource_$suf.a $PLASMA/PlanDatabase/objects/libPlanDatabase_$suf.a $PLASMA/ConstraintEngine/objects/libConstraintEngine_$suf.a $PLASMA/TinyXml/objects/libTinyXml_$suf.a $PLASMA/Utils/objects/libUtils_$suf.a
