package nddl;

interface NddlXmlStrings {
	public static final String x_name = "name";
	public static final String x_min = "min";
	public static final String x_max = "max";
	public static final String x_value = "value";
	public static final String x_extends = "extends";
	public static final String x_type = "type";
	public static final String x_basetype = "basetype";
	public static final String x_access = "access";
	public static final String x_native = "native";
	public static final String x_true = "true";
	public static final String x_false = "false";
	public static final String x_prototype = "prototype";
	public static final String x_float = "float";
	public static final String x_int = "int";
	public static final String x_boolean = "bool";
	public static final String x_string = "string";
	public static final String x_symbol = "symbol";
	public static final String x_relation = "relation";
	public static final String x_predicate = "predicate";
	public static final String x_class = "class";
	public static final String x_origin = "origin";
	public static final String x_target = "target";
	public static final String x_identifier = "identifier";
	public static final String x_mandatory = "mandatory";
	public static final String x_line = "line";
	public static final String x_column = "column";
	public static final String x_filename = "filename";
	public static final String x_inherited = "inherited";
};
