#!/bin/sh
# $Id: autobuild,v 1.14 2002-12-11 01:12:03 wedgingt Exp $
#
# Automatically build some variants of the Europa planner system

# Address to mail exit status messages to
email=checkins@postdoc.arc.nasa.gov

# Subdirectories to build in
#   Note that optimized variants take hours due to tokenNet test with -O3
#subdirs='cvs fast opt optFast prof profOptFast shareOptFast shareOptNoErr noErr'
subdirs='cvs fast opt optFast prof profOptFast noErr'

# Don't try to use X11 (mostly to prevent Purify from doing so)
DISPLAY=
export DISPLAY

# Apply limits; some compiles run out of swap space.
ulimit -c 200000
ulimit -d 1100000
ulimit -s 1100000
ulimit -v 1100000

# Print the limits so it is obvious what they are when something goes
# wrong.
ulimit -a

# Sometimes, this is run via cron, which does not use the usual $PATH
PATH=/usr/local/bin:/usr/local/teTeX/bin:"$PATH"
export PATH

CVSROOT=/home/cvs/ISG-Repository
export CVSROOT

set -x

startdir="`dirname $0`"
startdir="`cd $startdir; pwd`"

echo cd "$startdir"
cd "$startdir"

# Don't run this script more than once in the same directory.
mkdir working || exit 1

trap 'rmdir $startdir/working' 0

# Primary compilation loop
for dir in $subdirs
do

    cd "$startdir"
    if test -d "$dir"/NewPlan
    then
        echo "$0"': '"$dir"'/NewPlan already exists; exiting'
        exit 1
    fi

    if test ! -d "$dir"
    then
        mkdir "$dir"
        test $? = 0 || exit $?
    fi

    cd "$dir"

    cvs co NewPlan > cvs.co.NewPlan 2>&1
    status=$?
    echo '"cvs co NewPlan" in '"`pwd`"' exited '"$status"

    cd NewPlan

    mkdir working || continue

    if test "$status" != 0
    then
        mkdir working/cvs.co.failed
        exit "$status"
    fi

    if test -f ../make.options
    then
        # Add to commonMakeOptions.imake
        head -2 commonMakeOptions.imake > cMO.new
        cat ../make.options >> cMO.new
        echo '' >> cMO.new
        tail +3 commonMakeOptions.imake >> cMO.new
        mv -f cMO.new commonMakeOptions.imake
    fi

    test -d "$startdir"/working || exit 2

    make $makeopt tests >> make.tests 2>&1
    status=$?
    echo '"make tests" in '"`pwd`"' exited '"$status"

    if test $status = 0
    then
        /usr/ucb/Mail -s 'Autobuild in '"`pwd`"' succeeded' "$email" < ../make.options
    else
        ( cat ../make.options; echo ''; tail -40 make.tests) | \
            /usr/ucb/Mail -s 'Autobuild in '"`pwd`"' failed; exited '"$status" "$email"
        mkdir working/failed
    fi

    rmdir working || exit 1

    # Now, wipe out all that hard work
    cd "$startdir"/"$dir"

    rm -rf NewPlan

done
exit 0
