#!/bin/bash
# Run the Europa1 betaPlan program to compare performance with Europa2 (PLASMA).
# $Id: runBetaPlan,v 1.2 2004-12-27 22:14:14 wedgingt Exp $
date
hostname
pwd
betaPlan=../../../NewPlan/Planners/BetaPlanner/betaPlan
EUROPA_TIMINGS_RUN=2
export EUROPA_TIMINGS_RUN
if test ! -x "$betaPlan"
then
    echo 'Cannot find '"$betaPlan"
    exit 1
fi
ls -l satellites-*-*-*-*.ddl
for model in satellites-*-*-*-*.ddl
do
  init="`basename $model .ddl`".init
  test -s "$init" || continue
  date
  time "$betaPlan" -o none -m "$model" -i "$init"
  echo time "$betaPlan" -o none -m "$model" -i "$init" exited $?
done
date
